services:
  database:
    image: bitnami/postgresql:16.2.0
    environment:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_DATABASE: ignite-find-a-friend
    ports:
      - 5432:5432
  api:
    build:
      context: .
    ports:
      - 3333:3333
    env_file:
      .env.development
