name: Test

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.0.2

      - name: cache node_modules
        uses: actions/cache@v4
        id: pnpm-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: install node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.2
          cache: 'pnpm'

        if: steps.pnpm-cache.outputs.cache-hit != 'true'
      - run: pnpm install --prefer-offline --frozen-lockfile

      - name: run test coverage
        run: pnpm run test:coverage

